### PR TITLE
Color-coded JavaDocs for 1.2, 2.0, 2.1, 2.2, and 2.3

### PR DESCRIPTION
**Pull request by ngriffin7a**

### CODE REVIEW

**Review by edburns — CHANGES_REQUESTED** [review]
Hello Neil,

I'm sorry you went to the trouble of doing this.  We had the old jsf.java.net site migrated to <https://javaserverfaces.github.io/>.  Not all the links in that site have been updated yet.  I did just update the Documentation link for 2.2.  I would like to keep the javadoc over on the impl side, as we always have done.  So, if you want to submit another PR with just the javadoc index and the changes to the config.yml, that would be great.

Thanks,

Ed

**Comment by ngriffin7a** [comment]
@edburns It's OK -- I needed to do it because JSR 378 is a jump from JSF 1.2 -> 2.2, and I need to examine every color coded change in the JSF 2.0, 2.1, and 2.2 JavaDoc. I also find the 1.2 JavaDoc handy as I seek to better understand the mindset and decisions made by the JSR 329 EG. Before I send an updated PR with the JavaDoc index and config.yml, would you consider publishing the 1.2, 2.0, and 2.1 JavaDoc on the impl side as well?

**Review by edburns — APPROVED** [review]

**Comment by edburns** [comment]
I'm not sure what we should do with this PR.  I definitely don't want the full javadoc on the javaserverfaces-spec website.  But I am fine with having links to the javaserverfaces.github.io website docs.

**Comment by ngriffin7a** [comment]
Closing this PR. I will do as you asked and send a follow-up with the changes you requested to the javadoc index and the changes to the config.yml. The documentation link at https://javaserverfaces.github.io/ currently points to the 2.2 JavaDoc. Because of that, I did not realize that the JavaDoc for 2.3, 2.1, and 2.0 were working:
https://javaserverfaces.github.io/docs/2.3/javadocs/index.html
https://javaserverfaces.github.io/docs/2.1/javadocs/index.html
https://javaserverfaces.github.io/docs/2.0/javadocs/index.html

**Pull request closed without merging**
