### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by rajenderthota**
fix for typo in webpage (i.e. https://github.com/javaee/javaserverfaces-spec/issues/1474)

### CODE REVIEW

**Review by arjantijms — APPROVED** [review]

**Review by rajenderthota — COMMENTED** [review]
@arjantijms still I dont see this change not yet merged.

**Comment by BalusC** [comment]
This is the wrong site/repo. It is still associated with Oracle.
The correct site is the Eclipse-associated one: https://jakarta.ee/specifications/faces/
The current repo must be archived and the README must be updated to reflect that.

**Comment by rajenderthota** [comment]
@BalusC Thank you for the information.

**Comment by edbratt** [comment]
Thank you. I have corrected the typo

**Pull request closed without merging**
